use std::sync::Arc;

use async_trait::async_trait;
use axum::{Extension, Router};
use sdkwork_intelligence_webserver_service::WebService;
use sdkwork_routes_webserver_common::{
    web_auth_mode_from_env, with_problem_correlation, ProductionFailClosedResolver, WebAuthMode,
};
use sdkwork_web_axum::{with_web_request_context, WebFrameworkLayer};
use sdkwork_web_core::{
    DefaultWebRequestContextResolver, DomainContextInjector, WebAuthLevel, WebDeploymentMode,
    WebEnvironment, WebFrameworkError, WebLoginScope, WebRequestContext, WebRequestContextProfile,
    WebRequestContextResolver, WebRequestPrincipal, WebSubjectType,
};
use sdkwork_webserver_contract::WebBackendRequestContext;

use crate::http_route_manifest::backend_route_manifest;
use crate::paths;

/// Agent bootstrap token prefix (C8-C9).
/// Tokens generated by `WebRepository` follow the format `wagent_{uuid}`.
const AGENT_TOKEN_PREFIX: &str = "wagent_";

#[derive(Clone, Default)]
struct WebBackendContextInjector;

impl DomainContextInjector for WebBackendContextInjector {
    fn inject(&self, request: &mut axum::extract::Request, context: &WebRequestContext) {
        if let Some(backend_context) = web_backend_context_from_web_request(context) {
            request.extensions_mut().insert(backend_context);
        }
    }
}

fn web_backend_context_from_web_request(
    context: &WebRequestContext,
) -> Option<WebBackendRequestContext> {
    let principal = context.principal.as_ref()?;
    // tenant_id 解析失败时 fail-closed — 防止跨租户访问。
    let tenant_id: i64 = principal.tenant_id().parse().ok()?;
    // operator_id 解析失败不 fail-closed — agent-token 路由的 subject 是 UUID 字符串,
    // 无法解析为 i64,但 tenant 隔离仍然有效。
    let operator_id = principal.user_id().parse().ok();
    // subject_id 保存原始 principal user_id,agent-token 路由下为 server UUID。
    let subject_id = Some(principal.user_id().to_owned());
    Some(WebBackendRequestContext {
        operator_id,
        tenant_id: Some(tenant_id),
        subject_id,
    })
}

fn build_web_backend_api_framework_layer<R>(resolver: R) -> WebFrameworkLayer<R>
where
    R: WebRequestContextResolver + Clone,
{
    WebFrameworkLayer::new(resolver)
        .with_profile(WebRequestContextProfile {
            backend_api_prefix: paths::PREFIX.to_owned(),
            ..WebRequestContextProfile::default()
        })
        .with_route_manifest(backend_route_manifest())
        .with_domain_injector(Arc::new(WebBackendContextInjector))
}

/// Wraps an inner [`WebRequestContextResolver`] to intercept agent bootstrap tokens.
///
/// When `resolve_api_key` receives a credential prefixed with [`AGENT_TOKEN_PREFIX`]
/// (`wagent_`), the decorator authenticates it via [`WebService::try_authenticate_agent_token`]
/// and returns a [`WebRequestPrincipal`] with:
/// - `tenant_id` from the `web_server` row
/// - `user_id` set to the server UUID (available to handlers as `subject_id`)
/// - `subject_type = Service`, `auth_level = ApiKey`
/// - `permission_scope = ["web.agent.*"]` (authorizes agent routes)
///
/// Non-agent credentials are delegated to the inner resolver unchanged.
#[derive(Clone)]
pub struct AgentTokenResolverDecorator<R>
where
    R: WebRequestContextResolver,
{
    inner: R,
    service: Arc<WebService>,
}

impl<R> AgentTokenResolverDecorator<R>
where
    R: WebRequestContextResolver,
{
    pub fn new(inner: R, service: Arc<WebService>) -> Self {
        Self { inner, service }
    }
}

#[async_trait]
impl<R> WebRequestContextResolver for AgentTokenResolverDecorator<R>
where
    R: WebRequestContextResolver,
{
    async fn resolve_api_key(
        &self,
        raw_api_key: &str,
    ) -> Result<WebRequestPrincipal, WebFrameworkError> {
        if raw_api_key.starts_with(AGENT_TOKEN_PREFIX) {
            let (server_uuid, tenant_id) = self
                .service
                .try_authenticate_agent_token(raw_api_key)
                .await
                .map_err(|_| {
                    WebFrameworkError::invalid_credentials("invalid or expired agent token")
                })?;
            return Ok(WebRequestPrincipal::builder()
                .tenant_id(tenant_id.to_string())
                .login_scope(WebLoginScope::Tenant)
                .user_id(server_uuid)
                .app_id("sdkwork-web-agent")
                .environment(WebEnvironment::Prod)
                .deployment_mode(WebDeploymentMode::Saas)
                .auth_level(WebAuthLevel::ApiKey)
                .data_scope(vec![])
                .permission_scope(vec!["web.agent.*".to_owned()])
                .subject_type(WebSubjectType::Service)
                .build());
        }
        self.inner.resolve_api_key(raw_api_key).await
    }

    async fn resolve_dual_token(
        &self,
        raw_auth_token: &str,
        raw_access_token: &str,
    ) -> Result<WebRequestPrincipal, WebFrameworkError> {
        self.inner
            .resolve_dual_token(raw_auth_token, raw_access_token)
            .await
    }

    async fn resolve_access_token(
        &self,
        raw_access_token: &str,
    ) -> Result<WebRequestPrincipal, WebFrameworkError> {
        self.inner.resolve_access_token(raw_access_token).await
    }

    async fn resolve_oauth_bearer(
        &self,
        raw_bearer_token: &str,
    ) -> Result<WebRequestPrincipal, WebFrameworkError> {
        self.inner.resolve_oauth_bearer(raw_bearer_token).await
    }
}

pub async fn wrap_router_with_web_framework_from_env(
    router: Router,
    service: Arc<WebService>,
) -> Router {
    // Clone service for the resolver decorator before moving the original into Extension.
    let service_for_resolver = service.clone();
    // Extension(service) is applied inside the framework layer so that agent handlers
    // can extract Arc<WebService> alongside the framework-injected WebBackendRequestContext.
    let correlated = with_problem_correlation(router).layer(Extension(service));
    match web_auth_mode_from_env().await {
        WebAuthMode::DevInline => with_web_request_context(
            correlated,
            build_web_backend_api_framework_layer(AgentTokenResolverDecorator::new(
                DefaultWebRequestContextResolver::default(),
                service_for_resolver.clone(),
            )),
        ),
        WebAuthMode::ProductionFailClosed => with_web_request_context(
            correlated,
            build_web_backend_api_framework_layer(AgentTokenResolverDecorator::new(
                ProductionFailClosedResolver,
                service_for_resolver.clone(),
            )),
        ),
        WebAuthMode::IamDatabase(resolver) => with_web_request_context(
            correlated,
            build_web_backend_api_framework_layer(AgentTokenResolverDecorator::new(
                resolver,
                service_for_resolver.clone(),
            )),
        ),
    }
}
