// @generated by tools/materialize_web_phase1_contracts.mjs - do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest, RateLimitTier};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::ingress_token(
        HttpMethod::Put,
        "/internal/v3/api/web/runtime_assignments/{nodeUuid}/{environment}",
        "runtime",
        "runtimeAssignments.update",
    )
    .with_required_permission("web.runtimeAssignments.write")
    .with_idempotent(true)
    .with_rate_limit_tier(RateLimitTier::AuthCritical),
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/web/runtime_assignments/current",
        "runtime",
        "runtimeAssignments.current.retrieve",
    )
    .with_required_permission("web.agent.read"),
    HttpRoute::ingress_token(
        HttpMethod::Post,
        "/internal/v3/api/web/runtime_assignments/{snapshotUuid}/observations",
        "runtime",
        "runtimeAssignments.observations.create",
    )
    .with_required_permission("web.agent.write")
    .with_idempotent(true)
    .with_rate_limit_tier(RateLimitTier::AuthCritical),
];

pub fn internal_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
