apiVersion: v1
kind: Service
metadata:
  name: sdkwork-api-web-server-standalone-gateway-headless
  labels:
    app.kubernetes.io/name: sdkwork-web-server
    app.kubernetes.io/component: standalone-gateway
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: sdkwork-web-server
    app.kubernetes.io/component: standalone-gateway
  ports:
    - name: http
      port: 3800
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sdkwork-api-web-server-standalone-gateway
  labels:
    app.kubernetes.io/name: sdkwork-web-server
    app.kubernetes.io/component: standalone-gateway
spec:
  selector:
    app.kubernetes.io/name: sdkwork-web-server
    app.kubernetes.io/component: standalone-gateway
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
